"""M8 Trading Memory Package."""

from app.memory.analytics import (
    AnalyticsService,
    CalibrationEngine,
    HistoricalContextProvider,
    SimilarityEngine,
)
from app.memory.evaluator import PostTradeEvaluator, create_post_trade_evaluator
from app.memory.models import (
    DEFAULT_CALIBRATION_BUCKETS,
    DEFAULT_SIMILARITY_WEIGHTS,
    DEFAULT_THESIS_MATERIALITY_THRESHOLD_PCT,
    MIN_CALIBRATION_SAMPLE_SIZE,
    AgentPerformanceRecord,
    AgentStance,
    CalibrationBucket,
    CalibrationInsight,
    CalibrationSummary,
    CommitteePerformanceSummary,
    DisagreementAnalytics,
    DisagreementBucket,
    ExecutionQualityEvaluation,
    ExitQualityEvaluation,
    ExitReasonAnalytics,
    ExitReasonCategory,
    HistoricalContext,
    InstrumentOutcomeEvaluation,
    PerformanceSummary,
    RegimeAnalytics,
    RiskOutcomeEvaluation,
    RiskReductionAnalytics,
    SignalAttribution,
    SimilarityComponent,
    SimilarTradeResult,
    ThesisCorrectness,
    ThesisOutcomeEvaluation,
    TradeOutcome,
    TradeOutcomeType,
    TradeRecord,
    TrendRegime,
    get_default_calibration_buckets,
    get_default_similarity_weights,
)
from app.memory.service import TradingMemoryService, create_trading_memory_service
from app.memory.store import TradingMemoryStore, create_trading_memory_store

__all__ = [
    # Models
    "TradeRecord",
    "TradeOutcome",
    "TradeOutcomeType",
    "ThesisOutcomeEvaluation",
    "ThesisCorrectness",
    "ExecutionQualityEvaluation",
    "ExitQualityEvaluation",
    "RiskOutcomeEvaluation",
    "InstrumentOutcomeEvaluation",
    "AgentPerformanceRecord",
    "AgentStance",
    "CommitteePerformanceSummary",
    "CalibrationBucket",
    "CalibrationSummary",
    "CalibrationInsight",
    "DisagreementBucket",
    "TrendRegime",
    "ExitReasonCategory",
    "SimilarityComponent",
    "SimilarTradeResult",
    "HistoricalContext",
    "RiskReductionAnalytics",
    "RegimeAnalytics",
    "DisagreementAnalytics",
    "ExitReasonAnalytics",
    "SignalAttribution",
    "PerformanceSummary",
    "DEFAULT_THESIS_MATERIALITY_THRESHOLD_PCT",
    "MIN_CALIBRATION_SAMPLE_SIZE",
    "DEFAULT_CALIBRATION_BUCKETS",
    "DEFAULT_SIMILARITY_WEIGHTS",
    "get_default_calibration_buckets",
    "get_default_similarity_weights",
    # Store
    "TradingMemoryStore",
    "create_trading_memory_store",
    # Evaluator
    "PostTradeEvaluator",
    "create_post_trade_evaluator",
    # Analytics
    "CalibrationEngine",
    "SimilarityEngine",
    "HistoricalContextProvider",
    "AnalyticsService",
    # Service
    "TradingMemoryService",
    "create_trading_memory_service",
]